# Generated by Django 5.0.6 on 2024-05-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('maps_length', models.IntegerField()),
                ('maps_width', models.IntegerField()),
            ],
        ),
    ]
