# Generated by Django 5.0.6 on 2024-11-27 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='Registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
