# Generated by Django 5.0.6 on 2024-11-27 07:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0003_selled_maps_owner_delete_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('maps_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('maps_length', models.IntegerField()),
                ('maps_width', models.IntegerField()),
                ('Registered_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='selled_maps_owner',
            name='maps_id',
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='maps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BACKEND.maps'),
        ),
    ]
