# Generated by Django 5.0.6 on 2024-11-29 12:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0004_maps_remove_selled_maps_owner_maps_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner_name', models.CharField(default='Unknown', max_length=10)),
                ('owner_middle_name', models.CharField(default='Unknown', max_length=10)),
                ('owner_last_name', models.CharField(default='Unknown', max_length=10)),
                ('owner_address', models.CharField(default='Unknown', max_length=200)),
                ('owner_pan', models.CharField(default='Unknown', max_length=10)),
                ('owner_Addhar', models.CharField(default='Unknown', max_length=10)),
                ('Token_money', models.CharField(default='0', max_length=10)),
                ('total_maps_owned', models.IntegerField(default=0)),
                ('total_expends', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('seller_name', models.CharField(default='Unknown', max_length=10)),
                ('seller_middle_name', models.CharField(default='Unknown', max_length=10)),
                ('seller_last_name', models.CharField(default='Unknown', max_length=10)),
                ('seller_address', models.CharField(default='Unknown', max_length=200)),
                ('seller_pan', models.CharField(default='Unknown', max_length=10)),
                ('seller_Addhar', models.CharField(default='Unknown', max_length=10)),
                ('Token_money', models.CharField(default='0', max_length=10)),
                ('total_maps_owned', models.IntegerField(default=0)),
                ('total_earnings', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='selled_maps_owner',
            name='id',
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='owner_last_name',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='owner_middle_name',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='seller_Addhar',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='seller_address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='seller_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='seller_last_name',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='seller_middle_name',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='seller_name',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='seller_pan',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='total_earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selled_maps_owner',
            name='total_maps_owned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='selled_maps_owner',
            name='Token_money',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='selled_maps_owner',
            name='land_address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='selled_maps_owner',
            name='owner_Addhar',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='selled_maps_owner',
            name='owner_address',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='selled_maps_owner',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='selled_maps_owner',
            name='owner_pan',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
