# Generated by Django 5.0.6 on 2024-11-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0006_maps_maps_name_selled_maps_owner_maps_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='maps_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='selled_maps_owner',
            name='maps_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
