# Generated by Django 5.0.6 on 2024-11-29 12:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BACKEND', '0007_alter_maps_maps_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelledMapsOwner',
            fields=[
                ('Registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Token_money', models.CharField(default='0', max_length=10)),
                ('total_maps_owned', models.IntegerField(default=0)),
                ('total_earnings', models.IntegerField(default=0)),
                ('seller_owner_maps_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('maps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BACKEND.maps')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BACKEND.owner')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BACKEND.seller')),
            ],
        ),
        migrations.DeleteModel(
            name='selled_maps_owner',
        ),
    ]
